### PR TITLE
Db/access user data from callbacks

### PR DESCRIPTION
**Pull request by bennettbe**
As of now the user does not have a way to access their own data in the callbacks. This solves that problem. 

The problem arose when i was trying to queue a button event to a queue that was owned by a class.

### CODE REVIEW

**Comment by franz-ms-muc** [comment]
Hello. the Unit Test inside Button is not adopted. 
so it will not run.

**Comment by TDA-2030** [comment]
You are right! it needs more revision. :cry:

**Comment by bennettbe** [comment]
Thats right, ill fix that

**Comment by leeebo** [comment]
HELLO
IM LIBO
I HAVE GOT YOUR LETTER
PLEASE WAIT FOR REPLY

**Comment by TDA-2030** [comment]
To be honest, the unit-test-app in esp-iot-solution is out of date and cannot be compiled on the new IDF version. You can choose to test that in `esp-idf/tools/unit-test-app`.

You need to modify the `esp-idf/esp-idf-gitlab/tools/unit-test-app/CMakeLists.txt` file to add the components you want to test. As follows:
```
diff --git a/tools/unit-test-app/CMakeLists.txt b/tools/unit-test-app/CMakeLists.txt
index 9cab0436bc..a9fb7de355 100644
--- a/tools/unit-test-app/CMakeLists.txt
+++ b/tools/unit-test-app/CMakeLists.txt
@@ -2,7 +2,8 @@
 # CMakeLists in this exact order for cmake to work correctly
 cmake_minimum_required(VERSION 3.16)
 
-list(APPEND EXTRA_COMPONENT_DIRS "$ENV{IDF_PATH}/examples/cxx/experimental/experimental_cpp_component/")
+list(APPEND EXTRA_COMPONENT_DIRS "$ENV{IDF_PATH}/examples/cxx/experimental/experimental_cpp_component/"
+                                 "{your_path}/esp-iot-solution/components/button")
 
 include($ENV{IDF_PATH}/tools/cmake/project.cmake)
 project(unit-test-app)
```

**Comment by franz-ms-muc** [comment]
There is one more Error.
If you register 2 callbacks on 1 Button the 2nd Callback overwrite the usr_param from the first. I will make a pull request for fix this.

**Comment by franz-ms-muc** [comment]
https://github.com/espressif/esp-iot-solution/pull/201 here the Pull Request to fix the Test.

**Comment by franz-ms-muc** [comment]
here the 2nd Pull Request: 

fix the overwriting of usr_data

https://github.com/espressif/esp-iot-solution/pull/202

**Pull request closed without merging**
