### PR TITLE
Add Normal State, Fix C++ Compatibilty (AEGHB-337)

### PR DESCRIPTION
**Pull request by franz-ms-muc**
Add Normal State, Fix C++ Compatibilty

### CODE REVIEW

**Comment by franz-ms-muc** [comment]
@leeebo
i updated this to be in sync again with Master.

**Comment by leeebo** [comment]
Hi @franz-ms-muc sorry for the late response, Can you explain more about the application of this changes?

**Comment by lijunru-hub** [comment]
Due to significant changes in the 'button' component at present, many of the modifications in the pull request are no longer applicable. As a result, this pull request will not be merged. Thank you very much for your contribution.

**Comment by franz-ms-muc** [comment]
> Hi @franz-ms-muc sorry for the late response, Can you explain more about the application of this changes?

Hi @leeebo i will close this one, and submit new, with splitted into several PRs to get clearer overview.

**Comment by franz-ms-muc** [comment]
First one is here: https://github.com/espressif/esp-iot-solution/pull/326

**Comment by franz-ms-muc** [comment]
First one here: #327

**Comment by franz-ms-muc** [comment]
the second one was already fixed by putting "usr\_data" into a struct: 

see: https://github.com/espressif/esp-iot-solution/blob/996917bc7674f2392d676539809e14951694055c/components/button/iot_button.c#L36C1-L40C20

**Pull request closed without merging**
