### PR TITLE
feat: support uvc multiple bulk transfer per sample

### PR DESCRIPTION
**Pull request by leeebo**
Related https://github.com/espressif/esp-iot-solution/issues/360

### CODE REVIEW

**Comment by leeebo** [comment]
sha=ebcc082a97b0a06aa07ee5893f9c1fb6ab56cd8e

**Review by wujiangang — APPROVED** [review]

**Comment by wujiangang** [comment]
sha= ebcc082a97b0a06aa07ee5893f9c1fb6ab56cd8e

**Comment by leeebo** [comment]
the github action should be fixed in https://github.com/espressif/sync-pr-to-gitlab/pull/6

**Comment by leeebo** [comment]
sha=45a952d0418d0834062adf274bffbfa37ddafb47

**Pull request merged**
