### PR TITLE
Configuration descriptor larger than control transfer max length (AEGHB-57)

### PR DESCRIPTION
**Pull request by atamico**
I would like to know if anyone has already managed/tried to configure the ESP32s2 on communication pins 19, 20 as a USB-OTG port to connect other devices.

I want to make a Webserver with local ip, the same as ESP-CAM does, however, I want to use a USB Endoscopic USB camera (which is not possible with ESP-CAM).

I need help on How to use ESP32s2:

    Creating the Webserver_Cam
    Using USB model camera
    For Local ip.

I know it's possible because I saw it in an advertisement for "espressif".
~> https://youtu.be/RQOhrgRd7N8?t=55

Using my files available in GITHUB didn't work, it gives me an error with dempedencias, #Include, etc. When cloning a file folder the examples for solution (USB) are not integrated. 

Can someone help me?
(Scroll down to the bottom of the page/post for more details.)

### CODE REVIEW

**Comment by atamico** [comment]
> I would like to know if anyone has already managed/tried to configure the ESP32s2 on communication pins 19, 20 as a USB-OTG port to connect other devices.
> 
> I want to make...

Part of the solution was obtained using a Linux operating system for "Building".
The problem now is the configuration of the camera settings.
Any suggestions???
Below I put the camera configuration and then the error obtained.

**Comment by atamico** [comment]
CAMERA DETAILS


[CAM.txt](https://github.com/espressif/esp-iot-solution/files/9500866/CAM.txt)

**Comment by atamico** [comment]
**RETURN ERROR IN EXECUTION**

I (2260) camera_httpd: Starting web server on port: '80'
I (2268) camera_httpd: Starting stream server on port: '81'
I (2274) UVC_STREAM: UVC Streaming Config Succeed
I (2328) UVC_STREAM: UVC Streaming Starting
I (2358) UVC_STREAM: Port=1 init succeed
I (2358) UVC_STREAM: Waitting USB Connection
I (2608) UVC_STREAM: line 358 HCD_PORT_EVENT_CONNECTION
I (2608) UVC_STREAM: Resetting Port
I (2668) UVC_STREAM: Setting Port FIFO
I (2668) UVC_STREAM: Getting Port Speed
I (2668) UVC_STREAM: Port speed = 1
I (2670) UVC_STREAM: USB Speed: full-speed
I (2675) UVC_STREAM: Set Device Addr = 1
I (2680) UVC_STREAM: Set Device Addr Done
I (2684) UVC_STREAM: get device desc
I (2689) UVC_STREAM: get device desc, actual_num_bytes:26
*** Device descriptor ***
bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0xef
bDeviceSubClass 0x2
bDeviceProtocol 0x1
bMaxPacketSize0 64
idVendor 0x90c
idProduct 0x37c
bcdDevice 0.00
iManufacturer 1
iProduct 2
iSerialNumber 0
bNumConfigurations 1
I (2718) UVC_STREAM: get short config desc
I (2723) UVC_STREAM: get config desc, actual_num_bytes:16
**### E (2729) UVC_STREAM: Configuration descriptor larger than control transfer max length**                                                                             
I (2737) UVC_STREAM: Set Device Configuration = 1
I (2743) UVC_STREAM: Set Device Configuration Done
I (2748) UVC_STREAM: SET_CUR Probe
I (2753) UVC_STREAM: SET_CUR Probe Done
I (2757) UVC_STREAM: GET_CUR Probe
bmHint: 0000
bFormatIndex: 2
bFrameIndex: 5
dwFrameInterval: 333333
wKeyFrameRate: 0
wPFrameRate: 0
wCompQuality: 0
wCompWindowSize: 0
wDelay: 50
dwMaxVideoFrameSize: 769466222
dwMaxPayloadTransferSize: 832
dwClockFrequency: 0
bmFramingInfo: 0
bPreferredVersion: 0
bMinVersion: 0
bMaxVersion: 0
bInterfaceNumber: 0
I (2790) UVC_STREAM: GET_CUR Probe Done, actual_num_bytes:512
I (2796) UVC_STREAM: SET_CUR COMMIT
I (2801) UVC_STREAM: SET_CUR COMMIT Done
I (2805) UVC_STREAM: Set Device Interface = 1, Alt = 3
I (2840) UVC_STREAM: Set Device Interface Done
I (2840) UVC_STREAM: Sample processing task started
I (2890) UVC_STREAM: Camera Start Streaming
**W (3814) UVC_STREAM: line 677 Pipe: iso HCD_PIPE_EVENT_ERROR_OVERFLOW**

**Comment by leeebo** [comment]
@atamico Hi please try with the latest [driver ](https://github.com/espressif/esp-iot-solution/tree/master/components/usb/usb_stream) and [examples](https://github.com/espressif/esp-iot-solution/tree/master/examples/usb/host/usb_camera_mic_spk), and please close this PullRequest. If you have further questions please feel free to add [issues](https://github.com/espressif/esp-iot-solution/issues/new)

**Pull request closed without merging**
